postfix:
  image: muzili/centos-postfix
  environment:
    VIRTUAL_HOST: smtp.example.com
    DOMAIN_NAME: example.com
    SMTP_RELAY_HOST: smtp.mailgun.org
    SMTP_RELAY_PORT: 587
    SMTP_RELAY_USER: noreply@mg.example.com
    SMTP_RELAY_PASS: z1ggxPEAa33Rc
    SMTP_STARTTLS: true
    SMTP_PROTO: tls
  volumes:
    - ./data:/data
    - ./log:/var/log

